[package]
name = "uniremote-input"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
thiserror = "2"
unicase = "2"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = { version = "0.13", features = ["serde"] }

[features]
default = ["input-uinput"]
input-uinput = []
