[workspace]
members = ["core", "loader", "render", "input", "lua", "server"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.8", features = ["json"] }
mlua = { version = "0.11", features = ["lua54", "send"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
thiserror = "2.0"
xdg = "3.0"
dotenvy = "0.15"
serde = "1.0"
serde_json = "1.0"
serde-java-properties = "0.2"
quick-xml = "0.38"
