[package]
name = "uniremote-core"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
serde.workspace = true
serde_json.workspace = true

compact_str = { version = "0.9", features = ["serde"] }
thiserror = "2.0"
