[package]
name = "uniremote-render"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
uniremote-core = { path = "../core" }

axum.workspace = true
tracing.workspace = true

html-escape = "0.2"
